### ISSUE TITLE
ReactDOM.render is no longer supported in React 18. 

### ISSUE THREAD

**Issue by ramyakrishnai** [bluehost/bluehost-wordpress-plugin#1010]
**Summarize the issue (briefly)**

**Steps to reproduce**
  1. add `define( 'SCRIPT_DEBUG', true );` in wp-config.php
  2. Go to BH plugin dashbaord
  3. Click on any tabs in the sidemenu (marketplace, store etc)
  4. Open browser console

**Expected behavior**

We shouldn't be seeing this warnings which is coming for react.

**Screenshots**

<img width="1578" alt="Screenshot 2024-03-27 at 2 24 12 PM" src="https://github.com/bluehost/bluehost-wordpress-plugin/assets/80672694/a6745432-1516-4171-88e9-2f7941dd4ab6">

**Bluehost Plugin Version:**
* Version: 3.9.2

**Browser (with version) & Operating System (with version)**
  * Browser: Chrome
  * Operating System: MAC, Windows

**Comment by circlecube** [comment]
This was addressed in #575
