### ISSUE TITLE
nfd_wpnavbar_setting, Notice: Function wp_enqueue_script was called incorrectly.

### ISSUE THREAD

**Issue by cardfaux** [bluehost/bluehost-wordpress-plugin#1039]
**Summarize the issue (briefly)**

Got this error message: Notice: Function wp_enqueue_script was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the nfd_wpnavbar_setting handle. 
**Steps to reproduce**
  1. Go to...
  2. Click on...
  3. Scroll down to...
  4. See/experience error

**Expected behavior**

**Screenshots**

the problem was here and where it was being called above these lines in this function "set_wpnav_collapse_setting"
<img width="403" alt="Screenshot 2024-04-17 at 2 28 45 PM" src="https://github.com/bluehost/bluehost-wordpress-plugin/assets/54493199/2e6d8ffb-d05c-49f6-8d4e-5b107b27d659">

**Bluehost Plugin Version:**
* Version: 3.9.3

**Browser (with version) & Operating System (with version)**
  * Browser: Chrome
  * Operating System: MacOS
  * Device: m1. M1 Pro Laptop

**Additional context**

This file is in /vendor/newfold-labs/wp-module-ecommerce/includes/ECommerce.php

**Comment by chrisdavidmiles** [comment]
Thanks for the report @cardfaux - we will look into it and get it fixed in an upcoming release.

**Comment by chrisdavidmiles** [comment]
@cardfaux the fix for this is expected to be released May 1st in a new version of the plugin. Thanks again for the report.

**Comment by aratidgr8** [comment]
@chrisdavidmiles  Code fixes are completed. You can review the same in [PR](https://github.com/newfold-labs/wp-module-ecommerce/pull/296) 
cc: @cardfaux
