### ISSUE TITLE
Remove endurance module loader package

### ISSUE THREAD

**Issue by circlecube** [bluehost/bluehost-wordpress-plugin#166]
Once all dependencies are updated and/or removed, remove the old module loader package.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wpscholar** [comment]
There are only two packages that are dependent on the old module loader (and we have an issue created for each):

- Business Reviews: #163 
- Secure Passwords: #165

**Comment by circlecube** [comment]
Fixed with #233 !
