### ISSUE TITLE
CTB modal is cropped on mobile

### ISSUE THREAD

**Issue by circlecube** [bluehost/bluehost-wordpress-plugin#177]
**Summarize the issue (briefly)**
CTB modal windows are not very mobile friendly, the edges of the modal get cut off pretty severly on screens smaller than 500px. 

**Steps to reproduce**
  1. Open a CTB modal 
  2. Be on small screen
  4. See edges left and right get cropped off. Including image and copy.

**Expected behavior**
These should be flexible and have a max-width of around 5-600px and on mobile have a max width of 90-100%

**Screenshots**
<img width="410" alt="Screen Shot 2022-07-29 at 14 14 39" src="https://user-images.githubusercontent.com/698049/181825254-fb5734dd-e9ba-4e4d-b433-319e3c50a52a.png">

**Bluehost Plugin Version:**
* Version: 2.11.7

**Browser (with version) & Operating System (with version)**
  * Browser:
  * Operating System:
  * Device: All small

**Additional context**
This is in the ctb.css file, so it seems to be affecting every CTB, otherwise we could fix in a hiive template.

**Comment by aalani95** [comment]
Hey Evan, I created this PR to address it https://github.com/bluehost/bluehost-wordpress-plugin/pull/183
