### ISSUE TITLE
Enable Dependabot pull requests for third-party GitHub Actions

### ISSUE THREAD

**Issue by desrosj** [bluehost/bluehost-wordpress-plugin#221]
**Is your feature request related to a problem? Please describe.**
It's hard to keep dependencies up to date!

**Describe the solution you'd like**
By adding a Dependabot YML file, PRs for GHA updates can be created automatically. This will help us be better about keeping these actions updated, much like Dependabot does for NPM or Composer dependencies by default.

**Describe alternatives you've considered**
Manually checking for updates every so often.

**Additional context**
This could also create too much noise, and I know some people do not like Dependabot alerts as they can become annoying if too many updates become available in a short period of time. But I think it could be nice to keep an eye on the actions we utilize.

WordPress Core currently has a [version of this configuration file for this purpose](https://github.com/WordPress/wordpress-develop/blob/trunk/.github/dependabot.yml).

See also: [dependabot.yml documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file).

**Comment by circlecube** [comment]
This is in place here https://github.com/bluehost/bluehost-wordpress-plugin/blob/main/.github/dependabot.yml
