### ISSUE TITLE
Implement parallelization of Cypress tests pulled at the module level

### ISSUE THREAD

**Issue by wpscholar** [bluehost/bluehost-wordpress-plugin#277]
Currently, all of our tests are at the plugin level. We would like any tests related to our modules to be stored in the module repos and then run as part of the plugin-level tests. Any non-module or additional custom tests would be stored directly in the plugin.

https://www.youtube.com/watch?v=96Yn_IiQUJI

We can run groups of tests from the CLI by defining multiple `--spec` flags:

```
cypress run --base-url http://localhost:3000 --spec vendor/cypress/integration/**/*.js --spec tests/e2e/**/*.js
```

**Comment by wpscholar** [comment]
Could also be done like this:  https://docs.cypress.io/guides/guides/command-line#cypress-run-spec-lt-spec-gt:~:text=cypress%20run%20%2D%2Dspec%20%22cypress/e2e/examples/actions.cy.js%2Ccypress/e2e/examples/files.cy.js%22

**Comment by circlecube** [comment]
This is in place now. We've migrated the tests into the module and load them in the plugin cypress. Also using this (https://github.com/newfold-labs/workflows/blob/main/.github/workflows/module-plugin-test.yml) workflow to run plugin tests in each module before tagging a module release.
