### ISSUE TITLE
Set brand as origin if brand is empty

### ISSUE THREAD

**Issue by wpscholar** [bluehost/bluehost-wordpress-plugin#315]
**Is your feature request related to a problem? Please describe.**

Currently, we set a `$container->get('plugin')->id`, which gets passed as `origin` to the Hiive. We also send a `brand` property to the Hiive, which is the value of the `mm_brand` (soon to be `nfd_brand`) option. As such, we are getting a lot of empty brand values.

**Describe the solution you'd like**

We need to make sure we set the passed brand as either not empty, or we need to update the empty brand property to match the `origin` (plugin ID).

**Comment by circlecube** [comment]
This is in place here: https://github.com/bluehost/bluehost-wordpress-plugin/blob/main/bootstrap.php#L54
