### ISSUE TITLE
Build a CTB module and remove CTB functionality from plugin

### ISSUE THREAD

**Issue by circlecube** [bluehost/bluehost-wordpress-plugin#379]
**Is your feature request related to a problem? Please describe.**
In order to migrate to the newer plugin blueprint we need to move any one-off code from this plugin into a module for reuse in other brand plugins.

**Describe the solution you'd like**
We need to create a new `wp-module-ctb` module that contains all ctb functionality as is. Once we migrate to Jarvis we can simply update the module and can use it in any `isJarvis` sites.

**Describe alternatives you've considered**
Alternatively, we could sunset the CTB as sites are migrated since they will need to be rebuilt for Jarvis, but getting it into a module is something we can do now and then we are not blocked on migrating the plugin by hosting migrations.

**Additional context**

**Comment by earnjam** [comment]
This is closed as of #406
