### ISSUE TITLE
SiteInfoBar "Bluehost Account" link goes to wrong location in certain situations

### ISSUE THREAD

**Issue by earnjam** [bluehost/bluehost-wordpress-plugin#550]
For Jarvis sites, it appears the "Bluehost Account" link is pointing to the wrong location. I believe this stems from [cpanel not understanding how to redirect properly after login](https://github.com/bluehost/bluehost-wordpress-plugin/blob/main/src/app/components/site-info/index.js#L37).

The correct URL for Jarvis sites should be this: https://www.bluehost.com/my-account/hosting/details

This was reported by Chris Pond. Check with him if you have questions about proper situations and destination.

**Comment by ponddesign** [comment]
Hey @earnjam, @wpalani thanks for looking into this.

**Comment by ponddesign** [comment]
Are either of the following links a similar concern?

https://github.com/bluehost/bluehost-wordpress-plugin/blob/1be773f43268154dabce9fdc96a7c040e2ca9a6f/bootstrap.php#L113

https://github.com/bluehost/bluehost-wordpress-plugin/blob/bfc028d7499ee60e12ea9c7989492cfbce4340a1/inc/alt-experience/index.html#L136

**Comment by ponddesign** [comment]
Potential fix for the React link: #551
