### ISSUE TITLE
Cannot declare class Bluehost\Data

### ISSUE THREAD

**Issue by ael1875** [bluehost/bluehost-wordpress-plugin#638]
PHP Fatal error: When accessing the Menu option on the dashboard "There has been a critical error on this website" is displayed

**Steps to reproduce**
  1. Go to Wordpress Dashboard.
  2. Hover over Appearance and Click on Menu.

**Debug Error**
PHP Fatal error:  Cannot declare class Bluehost\Data, because the name is already in use in... /*****/*****/public_html/*****/wp-content/plugins/bluehost-wordpress-plugin/inc/Data.php on line 14

**Bluehost Plugin Version:**
* Version: 3.1.0 

**Browser (with version) & Operating System (with version)**
  * Browser: Firefox 116.0.3
  * Operating System: Windows 11 Home
  * Device: PC

**Comment by circlecube** [comment]
Thank you for reporting this issue @ael1875 

Are you also using the WP Mega Menu plugin (https://wordpress.org/plugins/wp-megamenu/)? I believe we found the issue and have a fix in place for it, but wanted to confirm this is the plugin you are seeing the conflict with.

**Comment by chrisdavidmiles** [comment]
I expect we'll have a fix for this in the next release in two weeks. Thanks for reporting this @ael1875 .

**Comment by ael1875** [comment]
Thank you @chrisdavidmiles

**Comment by circlecube** [comment]
This is included in the latest release, version 3.2.0. Thanks again @ael1875!
