### ISSUE TITLE
Issue with login redirect

### ISSUE THREAD

**Issue by sanzeeb3** [bluehost/bluehost-wordpress-plugin#74]
It looks like other user roles than administrator are also redirected to admin.php?page=bluehost#/home

which gives them a 'sorry you are not allowed to access this page' error message because they don't have capability to access that page.

There's possibly something to look into while checking administrator role.

**Comment by 0aveRyan** [comment]
Thank you for the report @sanzeeb3, we'll be looking into a solution for this!
