### ISSUE TITLE
wp-module-patterns breaks dynamic blocks

### ISSUE THREAD

**Issue by BrechtVds** [bluehost/bluehost-wordpress-plugin#759]
**Summarize the issue (briefly)**
The latest 3.4.2 version of the Bluehost plugin breaks dynamic blocks.

**Steps to reproduce**
1. Activate the Blue Host plugin
2. Add the default "Latest Comments" block in the Block Editor

Set up on example site with only the Bluehost plugin activated:
1. Login through magic link: https://app.instawp.io/wordpress-auto-login?site=$2y$10$ZxAE1euu2UWDsIMZc8tmGeTbaObQhlN/xPbrkCg9kGSI.ymi.8//6
2. Check out sample post with "Latest Comments" block: https://depressed-deer-inalc.instawp.xyz/wp-admin/post.php?post=1&action=edit

**Expected behavior**
The latest comments show up. Instead, you get a "Error loading block: Invalid parameter(s): attributes" error message. This is the full error:
`{"code":"rest_invalid_param","message":"Invalid parameter(s): attributes","data":{"status":400,"params":{"attributes":"nfdGroupDivider is not a valid property of Object."},"details":{"attributes":{"code":"rest_additional_properties_forbidden","message":"nfdGroupDivider is not a valid property of Object.","data":null}}}}`

**Bluehost Plugin Version:**
* Version: 3.4.2

**Browser (with version) & Operating System (with version)**
  * Browser: Safari 16.6
  * Operating System: MacOS 13.5
  * Device: Mac Mini

**Additional context**
Seems to be related to the newfold-labs/wp-module-patterns library, which was updated.
As far as I can tell **all** dynamic blocks are broken by the Bluehost plugin. It came on my radar because it breaks the recipe block of my WP Recipe Maker plugin. Several customers have contacted me about this issue, so it would be great if this could get resolved soon. Thanks!

**Comment by circlecube** [comment]
Thanks again for the heads up here, this has been fixed as of plugin version [`3.5.0`](https://github.com/bluehost/bluehost-wordpress-plugin/releases/tag/3.5.0) and `wp-module-patterns` [`0.1.7`](https://github.com/newfold-labs/wp-module-patterns/releases/tag/0.1.7) which includes this fix: https://github.com/newfold-labs/wp-module-patterns/pull/29
