### ISSUE TITLE
Respect Jetpack SSO Settings

### ISSUE THREAD

**Issue by bobmatyas** [bluehost/bluehost-wordpress-plugin#815]
**Summarize the issue (briefly)**

The plugin enables Jetpack's SSO module regardless of user preference. I encountered a situation where this plugin kept turning SSO on despite the customer's preference. 

**Steps to reproduce**
  1. Add Bluehost and Jetpack Plugins.
  2. Turn off SSO in Jetpack
  3. The Bluehost will turn the plugin back on
  4. See/experience error

**Expected behavior**

The plugin should respect the user's Jetpack settings. 

Alternatively, the plugin should indicate what modules can't be disabled.

**Additional context**

Code: 
https://github.com/bluehost/bluehost-wordpress-plugin/blob/f8e296da09693edf24188578e1308bd8ca44d2a1/inc/jetpack.php#L17-L23

Workaround that requires users to add custom code:

https://wordpress.org/support/topic/jetpack-sso-module-turning-on-seemingly-by-itself/#post-15545485

**Comment by wpscholar** [comment]
Thanks for reporting this @bobmatyas. We're working to address this.

**Comment by wpscholar** [comment]
This appears to no longer be an issue.
