### ISSUE TITLE
Bluehost Plugin changes WooCommerce Shortcode Checkout fields when enabled and using “Default to customer shipping address”

### ISSUE THREAD

**Issue by darcie** [bluehost/bluehost-wordpress-plugin#905]
**Summarize the issue (briefly)**

We've recently been getting reports in WooCommerce support of merchants missing emails or phone numbers when customers place orders. We've narrowed this down to happening when The Bluehost plugin is enabled and the merchant is using “Default to customer shipping address” in their shipping options. 

This lack of billing fields in the expected location is causing orders to fail or not have enough information for the store owner to complete the order. 

**Steps to reproduce**
  1. Have a site with only WooCommerce and The Bluehost Plugin installed
  2. Use the shortcode based checkout [woocommerce_checkout] or the Classic Checkout block, this does not affect the Blocks based checkout.
  3. Select “Default to customer shipping address” in WooCommerce > Settings > Shipping > Shipping settings
  4. Add a product to the cart and visit checkout 
  5. Notice there is no email or phone field available to enter
  6. Only if "Bill to a different address?” is selected, the expected billing fields are shown
  7. Disable The Bluehost Plugin and refresh the checkout page
  8. The expected billing fields appear at checkout. 

**Expected behavior**

I expected the billing and shipping fields to remain with the same with or without The Bluehost Plugin enabled on a site. 

**Screenshots**

With The Bluehost Plugin: 
![screencapture-moon-of-chopshops-jurassic-ninja-checkout-2024-01-23-18_36_18](https://github.com/bluehost/bluehost-wordpress-plugin/assets/318285/3ce6d559-3d2a-43f8-8ba8-33ef63c29279)

Without The Bluehost Plugin: 
![screencapture-moon-of-chopshops-jurassic-ninja-checkout-2024-01-23-18_36_57](https://github.com/bluehost/bluehost-wordpress-plugin/assets/318285/7866f7be-fa3f-4edc-96a0-7f578ce2295c)

**Bluehost Plugin Version:**
* Version: 3.8.2

Introduced in 3.8.0, reverting to 3.7.3 also resolves the issue. 

**Additional context**

**Comment by darcie** [comment]
Doing some additional digging, it looks like that was changed with this PR: https://github.com/newfold-labs/wp-module-ecommerce/pull/189
However, as visible in the screenshot, the email and phone are not visible until "Bill to a different address?" is selected.

**Comment by clifgriffin** [comment]
This creates major problems beyond the shortcode. The Bluehost Plugin is forcibly swapping the shipping and billing fields in all cases where the default customer address is set to the shipping address.

**Comment by circlecube** [comment]
This has been fixed since plugin version 3.8.4

**Comment by darcie** [comment]
> This has been fixed since plugin version 3.8.4

@circlecube This was resolved by https://github.com/newfold-labs/wp-module-ecommerce/pull/208, but WooCommerce Support continues to receive support requests related to this even for stores on 3.9.1. Either customers cannot proceed due to missing email and phone fields, or payment gateways receive errors for missing data. The only resolution is to disable The Bluehost Plugin or revert to defaulting to customer billing address. 

I highly recommend further testing.

**Comment by circlecube** [comment]
Thanks for letting us know @darcie - we'll check on it again.

**Comment by chrisdavidmiles** [comment]
@darcie We found where the problem was coming from and have a fix ready. A new release of the Bluehost plugin (version 3.9.3) is expected to be released in a few hours. The problem should be resolved then for anyone running that version of the plugin or newer.

**Comment by darcie** [comment]
Thanks for the update, @chrisdavidmiles! I'll let the rest of Woo Happiness know as well! :)
