### ISSUE TITLE
PHP Warning:  Undefined array key in PluginsController.php on line 84

### ISSUE THREAD

**Issue by TheLolokio** [bluehost/bluehost-wordpress-plugin#970]
**Summarize the issue (briefly)**
With this plugin installed on my bluehost site, my cPanel error log under public_html reports repeating PHP warnings for the PluginsController.php file. 

**PHP Warning: Undefined array key "file_premium" in [my site path]/wp-content/plugins/bluehost-wordpress-plugin/vendor/newfold-labs/wp-module-ecommerce/includes/RestApi/PluginsController.php on line 84**

**PHP Warning:  Undefined array key "file_extented" in [my site path]/wp-content/plugins/bluehost-wordpress-plugin/vendor/newfold-labs/wp-module-ecommerce/includes/RestApi/PluginsController.php on line 84**

I am currently running the most recent Bluehost Plugin version (3.9.0) and using PHP version 8.3, but this error occurred on 8.2 as well. 

With the plugin installed, my site is unstable and will eventually crash with an Internal Server Error: 500. 

Removing the .htaccess file resolves this behavior, temporarily. 

Bluehost support has suggested that I disable the bluehost plugin, however -- this greatly impacts the layout / visuals of my site. 

**Steps to reproduce**
  1. Install Bluehost Plugin
  2. Load Website
  3. Wait until bug presents (errors show up consistently in error logs, but bug timing seems to increase with more page loads + attempts to edit the site) 
 4. Internal Server Error 500 on both Wordpress Editor and public site. 

**Expected behavior**
Proper site load

**Bluehost Plugin Version:**
* Version: 3.9.0

**Browser (with version) & Operating System (with version)**
  * Browser: Mozilla Firefox v123 (64-bit)
  * Operating System: Windows 11
  * Device: PC

**Additional context**
This issue began at the beginning of February, I am considering loading an older branch to see if it resolves my issue. 

Bluehost support has also scanned my site for malware with no results found, and confirmed PHP admin looked clear. I was told this is a known issue and my domain was added to the trouble ticket.

Other plugins I have installed: 
![image](https://github.com/bluehost/bluehost-wordpress-plugin/assets/162067465/e713f7e4-0a78-4aee-833c-c55d3737ff8f)

**Comment by sihagm** [comment]
I have the same problem:

[05-Mar-2024 17:58:30 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function NewfoldLabs\WP\Module\Data\data_get() in /home3/xxx/public_html/wp-content/plugins/bluehost-wordpress-plugin/vendor/newfold-labs/wp-module-data/includes/Data.php:131
Stack trace:
#0 /home3/xxx/public_html/wp-includes/class-wp-hook.php(324): NewfoldLabs\WP\Module\Data\Data->authenticate(NULL)
#1 /home3/xxx/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
#2 /home3/xxx/public_html/wp-includes/rest-api/class-wp-rest-server.php(189): apply_filters('rest_authentica...', NULL)
#3 /home3/xxx/public_html/wp-includes/rest-api/class-wp-rest-server.php(428): WP_REST_Server->check_authentication()
#4 /home3/xxx/public_html/wp-includes/rest-api.php(424): WP_REST_Server->serve_request('/wp/v2/media')
#5 /home3/xxx/public_html/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#6 /home3/xxx/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#7 /home3/xxx/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#8 /home3/xxx/public_html/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#9 /home3/xxx/public_html/wp-includes/class-wp.php(813): WP->parse_request('')
#10 /home3/xxx/public_html/wp-includes/functions.php(1336): WP->main('')
#11 /home3/xxx/public_html/wp-blog-header.php(16): wp()
#12 /home3/xxx/public_html/index.php(17): require('/home3/oxwmahmy...')
#13 {main}
  thrown in /home3/xxx/public_html/wp-content/plugins/bluehost-wordpress-plugin/vendor/newfold-labs/wp-module-data/includes/Data.php on line 131

**Comment by TheLolokio** [comment]
Update to this, I continued to have the issue with 3.9.0 AND 3.91. 

Rolling my site back to 3.7.0 and disabling auto updates seems to have worked for now, I'm going to continue to monitor and see if the issue recurs.

**Comment by TheLolokio** [comment]
Nope, that wasn't good enough. Issue recurred. 

I'm also trying PHP version 7.4, per BlueHost support.

**Comment by TheLolokio** [comment]
That also did not work -- issue recurred. 

At this point I'm combing through my site to see what CSS is modified by the bluehost plugin so I can leave it deactivated.

**Comment by TheLolokio** [comment]
I've had the plugin removed for 4 days without the issue recurring. 

I had to redesign the elements of the page that were broken with the plugin being removed, I had no idea that the Bluehost plugin was impacting the editor -- nothing in its description would make you think that it impacted the design side of things. 

I will not be installing this plugin on any of my future sites, not worth the headache. Thanks for the quick response and help here on GitHub and from Bluehost support!! /s 

Good luck to future folks who face this issue.

**Comment by gillens** [comment]
I am getting I think the same error, although it's not visible on the browser-side. It seems to be logged when I log in to wordpress, and sometimes when I browse around the admin dashboard. The errors started Feb 29 2024, when my Bluehost plugin was updated from version 3.8.4 to 3.9.0.

This piece of code is from the included [wp-module-ecommerce](https://github.com/newfold-labs/wp-module-ecommerce/), and the problem code seems to have been introduced in that module's version 1.3.22 (1.3.23 was included here with version 3.9.0).

The new release 1.3.24 of wp-module-ecommerce seems to address this, and the pull request for the next release (3.9.2) updates to that. So if you have any interest in reinstalling @TheLolokio , I think it will be fixed soon.

**Comment by gillens** [comment]
Just updated bluehost plugin to 3.9.2 (just released) and I'm not seeing the errors from wp-module-ecommerce anymore. I think this is fixed now. Thanks for the resolution @circlecube!

**Comment by circlecube** [comment]
Awesome, thank you for confirming @gillens 

I'll close this out, and if anyone sees these again please open a new issue!
